### ISSUE TITLE
Updating Project Name

### ISSUE THREAD

**Issue by Marak** [LolaShare/LolaShare#56]
As the team has been discussing over the past weeks, we are going to update from our Alpha codename of "Ferment" to our new application name "LolaShare".

I'm creating this issue to help track commits related to updating places in the code where "Ferment" may be hard-coded.

New website and branding will be coming out in the next few days.

**Comment by ahdinosaur** [comment]
and we're back to ferment meow: https://github.com/LolaShare/LolaShare/pull/66
