### ISSUE TITLE
Can't add audio in Windows

### ISSUE THREAD

**Issue by bumcheekcity** [LolaShare/LolaShare#62]
Open the program, click "add audio" and select any mp3 file on Linux (Debian) works fine. On Windows, it pops up an error message saying 

`An error occurred while processing audio file. Please check that the file is in a supported format. 

spawm ffmpeg ENOENT`

And the following prints in the console:

> { Error: spawn ffmpeg ENOENT
>     at exports._errnoException (util.js:1026:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>   code: 'ENOENT',
>   errno: 'ENOENT',
>   syscall: 'spawn ffmpeg',
>   path: 'ffmpeg',
>   spawnargs:
>    [ '-i',
>      'K:\\iPod Organised Folder\\Music\\Music\\Jonathan Coulton\\Thing a Week\\2
> -09 Take Care of Me.mp3',
>      '-ac',
>      1,
>      '-filter:a',
>      'aresample=1000',
>      '-map',
>      '0:a',
>      '-c:a',
>      'pcm_s8',
>      '-f',
>      's8',
>      'pipe:1' ],
>   cmd: 'ffmpeg -i K:\\iPod Organised Folder\\Music\\Music\\Jonathan Coulton\\Thi
> ng a Week\\2-09 Take Care of Me.mp3 -ac 1 -filter:a aresample=1000 -map 0:a -c:a
>  pcm_s8 -f s8 pipe:1' }

**Comment by Marak** [comment]
Good catch.

Related #30, Item 1.

We need to have an ffmpeg binary shipped and available for the system. I haven't tried this before, but I'm guessing we can use the binaries found here: http://ffmpeg.zeranoe.com/builds/

You could probably start testing by downloading the windows binary manually and try pointing to the location. Let me know if you figure anything out. I do have a windows machine here for testing as well.

**Comment by mmckegg** [comment]
I used a very specific build of ffmpeg to reduce file size and ensure the correct codecs were in place. It would be very hard to find a prebuilt version that had all the right codecs and not 20 MB. My current build is ~2 MB i seem to recall.

Here's a script to build on Mac + Linux: https://github.com/LolaShare/LolaShare/blob/master/scripts/build-ffmpeg.sh

I managed to build it for windows on linux using https://github.com/rdp/ffmpeg-windows-build-helpers, but this was for a different project -- I'll see if I can find the script

**Comment by Marak** [comment]
If we need to start by packaging the 20 MB version for windows to get us working immediately, we could in theory always optimize this later.

@mmckegg - Would be nice to have that script if you can find it. If not, we can attempt to make a new one.

**Comment by bumcheekcity** [comment]
Well, the plus side is that the attached fix does work. The minus side is the precompiled binary is 40MB.

**Comment by Marak** [comment]
Tracking new issue for optimization at #64
